modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="ostrea"
version="1.2.0.0"
displayName="Ostrea"
logoFile="ostrea_logo.png"
authors="Tortugolen"
description='''OYSTERS!!!'''

[[dependencies.ostrea]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ostrea]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ostrea]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="NONE"
side="BOTH"